# Generated by Django 3.0.2 on 2020-01-29 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
            preserve_default=False,
        ),
    ]
